model: mistral-ai/Ministral-3B
maxTokens: 1000
responseFormat: json_schema
jsonSchema: |-
  {
    "name": "content_audit_feedback",
    "strict": true,
    "schema": {
      "type": "object",
      "properties": {
        "outdated": {
          "type": "boolean",
          "description": "Indicates that the content is outdated and needs to be updated"
        },
        "suggestions": {
          "type": "string",
          "description": "Detailed suggestions for improving the content"
        }
      },
      "additionalProperties": false,
      "required": [
        "outdated",
        "suggestions"
      ]
    }
  }
messages:
  - role: system
    content: {{ prompt }}